version: '3.8'

services:
  auth-service:
    build: ./auth-service/.
    container_name: auth-service
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:80"

  db:
    image: postgres:13
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  account_service:
    build: .
    container_name: account_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - DEBUG=${DEBUG}
    env_file:
      - .env

volumes:
  postgres_data:
