global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']
    metrics_path: /metrics
    scheme: http

  - job_name: 'account-service'
    static_configs:
      - targets: ['account-service:8001']
    metrics_path: /metrics
    scheme: http

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['localhost:8002']
    metrics_path: /metrics
    scheme: http

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8003']
    metrics_path: /metrics
    scheme: http

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
