global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:80']
    metrics_path: /metrics
    scheme: http

  - job_name: 'account-service'
    static_configs:
      - targets: ['account-service:80']
    metrics_path: /metrics
    scheme: http

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:80']
    metrics_path: /metrics
    scheme: http

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:80']
    metrics_path: /metrics
    scheme: http

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
