version: "3.9"
services:
  python-app:
    build: .
    container_name: python-app-container
    depends_on:
      - db
    ports:
      - "8000:8000"  # Прокси-порт 8000
    volumes:
      - .:/app  # Монтируем директорию проекта внутрь контейнера

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      
volumes:
  db_data: