apiVersion: v1
data:
  create-multiple-dbs.sh: |
    #!/bin/bash
    set -e

    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
        echo "Creating multiple databases: $POSTGRES_MULTIPLE_DATABASES"
        for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
            echo "Creating database $db"
            psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
                CREATE DATABASE $db;
    EOSQL
        done
        echo "Multiple databases created"
    fi
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: db
  name: db-cm0
