apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: transaction-service
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transaction-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: transaction-service
    spec:
      containers:
        - env:
            - name: ALGORITHM
              valueFrom:
                configMapKeyRef:
                  key: ALGORITHM
                  name: transaction-service-env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: transaction-service-env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: transaction-service-env
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: transaction-service-env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: transaction-service-env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: transaction-service-env
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: transaction-service-env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: transaction-service-env
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  key: JWT_ALGORITHM
                  name: transaction-service-env
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET_KEY
                  name: transaction-service-env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: transaction-service-env
          image: transaction-service
          name: transaction-service
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /app/logs
              name: transaction-service-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: transaction-service-cm0
          name: transaction-service-cm0
